export const AUTH_LOGIN_INPUT_HANDELING = 'AUTH_LOGIN_INPUT_HANDELING';
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const AUTH_LOGOUT_HANDLE = 'AUTH_LOGOUT_HANDLE';
export const SIGN_UP_INPUT_HANDELING = 'SIGN_UP_INPUT_HANDELING';
export const HANDLE_SUBMIT_SIGN_UP = 'HANDLE_SUBMIT_SIGN_UP';
export const SIGN_UP_STATUS_CLEAN = 'SIGN_UP_STATUS_CLEAN';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const HANDLE_PROFILE_INPUT_CHANGE = 'HANDLE_PROFILE_INPUT_CHANGE';
export const HANDLE_PROFILE_UPDATE = 'HANDLE_PROFILE_UPDATE';

